name: 'Magento 2 Coding Style'
author: 'EcomEU'
description: 'performs php static code analysis with the Magento 2 Coding Standard'
inputs:
  phpcs_standard:
    description: 'Path to your own PHPCS file or a specific standard. Leave empty to use "Magento2".'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path_to_scan }}
branding:
  icon: 'code'  
  color: 'green'
